format = """
$os\
$directory\
$character
"""
[os]
disabled = false

[os.symbols]
Arch = "󰣇 "

[directory]
format = "[$path]($style) "
truncation_length = 3
truncate_to_repo = true
home_symbol = "~"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = "󰝚 "
"Pictures" = " "
"Developer" = "󰲋 "
"Videos" = " "
