font_family	JetBrainsMono Nerd Font
font_size	10.5


# bell
enable_audio_bell	no
window_alert_on_bell	yes
bell_on_tab	no
window_padding_width 10


# map
map ctrl+alt+right next_tab
map ctrl+alt+left previous_tab
